# Scalars

## Scalars in Python

In [2]:
x = 25
x

25

In [3]:
type(x)

int

In [4]:
y = 3

In [5]:
py_sum = x + y
py_sum

28

In [6]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [7]:
type(float_sum)

float

## Scalars in Pytorch

In [8]:
import torch

In [9]:
x_pt = torch.tensor(25, dtype=torch.float16)
x_pt

tensor(25., dtype=torch.float16)

In [10]:
x_pt.shape

torch.Size([])

## Scalars in TensorFlow

In [11]:
import tensorflow as tf

2025-03-26 09:42:17.845629: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [12]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [13]:
x_tf.shape

TensorShape([])

In [14]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [15]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [16]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [17]:
tf_sum.numpy()

28

In [18]:
type(tf_sum)

tensorflow.python.framework.ops.EagerTensor

In [19]:
type(tf_sum.numpy())

numpy.int16

In [20]:
tf_float = tf.Variable(25, dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

# Vectors

## Vector in Numpy

In [21]:
import numpy as np

In [22]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [23]:
len(x)

3

In [24]:
x.shape

(3,)

In [25]:
type(x)

numpy.ndarray

In [26]:
type(x[0])

numpy.int64

In [27]:
y = np.array([[25, 2, 5]])
len(y)

1

In [28]:
type(y)

numpy.ndarray

In [29]:
y.shape

(1, 3)

In [30]:
y_t = y.T

In [31]:
print("Normal")
print(y)
print()
print("Transpose")
print(y_t)

Normal
[[25  2  5]]

Transpose
[[25]
 [ 2]
 [ 5]]


## Zero Vectors

In [32]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in Pytorch and Tensorflow

In [33]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [34]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

## Basis Vectors

- They are vectors that can be scaled to represent any vector in an given vector space.
- For this purpose we use unit vectors along axes of vector space

## Orthogonal Vectors

- **x** and **y** are orthogonal vectors if **x<sup>T</sup>y = 0**
- Are at 90<sup>o</sup> angle to each other and have non zero non (non zero length).

In [44]:
i = np.array([1, 0])
i

array([1, 0])

In [45]:
j = np.array([0, 1])
j

array([0, 1])

In [46]:
np.dot(i, j)

0

# Norms


1. Norms are functions that quantify vector magnitude.
2. Of all the norm functions the most common is L2 norm.

The formula for the **L2 norm** (also known as the Euclidean norm) of a vector $( x_1, x_2, \dots, x_n)$ is given by:

$$
\| \mathbf{x} \|_2 = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2}
$$

Where:
- $\|\mathbf{x}\|$  is a vector $\mathbb{R}^n$,
- $( x_1, x_2, \dots, x_n)$ are the components of the vector.

This represents the "straight-line" distance from the origin to the point represented by the vector in Euclidean space.

$\| \mathbf{x} \|_2$ can also be denoted by $\| \mathbf{x} \|$

## L2 Norm Calculation using python

In [36]:
x

array([25,  2,  5])

In [37]:
l2_norm = pow(x[0]**2 + x[1]**2 + x[2]**2, 0.5)
l2_norm

25.573423705088842

## L2 Norm Calculation using library

In [38]:
np.linalg.norm(x)

25.573423705088842

## Unit Vectors

vectors whose **L2 Norm** is equal to 1 are called unit vectors

## L1 Norms

L1 norms are just absolute addition of values
They are usefull in scenarios where difference between zero and nonzero is a key

L1 norm is calculated via $\| \mathbf{x} \|_1 = (abs(x_1) + abs(x_2) + \dots + abs(x_n))$


In [39]:
x

array([25,  2,  5])

In [40]:
l1_norm_simple = abs(25) + abs(2) + abs(5)
l1_norm_np = np.abs(25) + np.abs(2) + np.abs(5)

In [41]:
print(l1_norm_simple, l1_norm_np)

32 32


In [42]:
x = np.array([[1,2], [3,4]])
np.dot(x, x)

array([[ 7, 10],
       [15, 22]])

## MAX Norm

This is just taking the maximum of abs value of largest element

# Matrix (2 dimensional Tensors)

- Matrixes are just 2 dimensional array of numbers.
- Denoted in uppercase, italics, bold, e.g.:X
- Height given proirity than width in notation like x<sub>row, col</sub>


In [47]:
x = np.array([[25, 2], [5, 26], [3, 7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [48]:
x.shape

(3, 2)

In [49]:
x.size

6

In [52]:
x[1,:] ## middle row

array([ 5, 26])

In [92]:
x[:,1] ## rightmost column

array([ 2, 26,  7])

In [87]:
x[0:2]

array([[25,  2],
       [ 5, 26]])

In [77]:
x[0:2, 1:]

array([[ 2],
       [26]])

## Matices in PyTorch

In [93]:
X_pt = torch.tensor([[25, 2], [5, 6], [3, 7]])
X_pt

In [94]:
X_pt.shape

torch.Size([3, 2])

In [95]:
X_pt[1,:]

tensor([5, 6])

## Matrices in TensorFlow

In [102]:
X_tf = tf.Variable([[25, 2], [5, 6], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5,  6],
       [ 3,  7]], dtype=int32)>

In [103]:
X_tf.shape

TensorShape([3, 2])

In [104]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [105]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [107]:
X_tf[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 6, 7], dtype=int32)>

# Higher-Rank Tensors

In [111]:
images_pt = torch.zeros([32, 28, 28, 3])
#images_pt

In [114]:
images_tf = tf.zeros([32, 28, 28, 3])
#images_tf