# Frobenius Norm

The frobenius norm is the square root of sum of square of all elements in the matrix

In [5]:
import numpy as np

In [6]:
X = np.array([[1,2], [3,4]])

In [7]:
np.linalg.norm(X)

5.477225575051661

In [9]:
import torch

In [16]:
X_pt = torch.tensor([[1,2], [3,4]], dtype=torch.float)

In [17]:
torch.norm(X_pt)

tensor(5.4772)

In [18]:
import tensorflow as tf

2025-07-16 01:17:32.837393: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [24]:
X_tf = tf.Variable([[1,2], [3,4]], dtype=float)

In [25]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.4772257804870605>

# Matrix Multiplication

In [30]:
A = np.array([[3,4], [5,6], [7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [31]:
B = np.array([1, 2])
B

array([1, 2])

In [32]:
np.dot(A, B)

array([11, 17, 23])

In [40]:
A_pt = torch.tensor([[3,4], [5,6], [7,8]])
A_pt.shape

torch.Size([3, 2])

In [43]:
B_pt = torch.tensor([1,2])
B_pt.shape

torch.Size([2])

In [36]:
torch.matmul(A_pt, B_pt)

tensor([11, 17, 23])

In [44]:
A_tf = tf.Variable([[3,4], [5,6], [7,8]])
B_tf = tf.Variable([1, 2])

In [45]:
tf.linalg.matvec(A_tf, B_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

# Matrix Inversion

In [46]:
X = np.array([[4,2], [-5,-3]])

In [49]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [50]:
y = np.array([4, -7])

In [51]:
w = np.dot(Xinv, y)
w

array([-1.,  4.])

In [53]:
y_checked = np.dot(X, w)
y_checked

array([ 4., -7.])

# Orthogonal Matrix

In orthogonal matrix orthonormal vectors make up all rows and all columns

So thats why taking A<sup>T</sup>A = AA<sup>T</sup> = I

That means A<sup>T</sup> = A<sup>-1</sup>