# Tensor Transposition

In [1]:
import torch
import tensorflow as tf

2025-07-16 00:48:30.789183: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [3]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [4]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [5]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

# Basic Tensor Arithmetic

In [6]:
X_pt * 2

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [7]:
X_pt + 2

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [8]:
X_pt * 2 + 2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [9]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [10]:
X_tf * 2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[50,  4],
       [10, 52],
       [ 6, 14]], dtype=int32)>

In [11]:
X_tf + 2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[27,  4],
       [ 7, 28],
       [ 5,  9]], dtype=int32)>

In [12]:
X_tf * 2 + 2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [13]:
tf.add(tf.multiply(X_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

# Tensor Reduction

In [15]:
X_pt.sum()

tensor(68)

In [16]:
X_pt.sum(axis=0)

tensor([33, 35])

In [17]:
X_pt.sum(axis=1)

tensor([27, 31, 10])

In [18]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10], dtype=int32)>